index:
    path: /
    controller: App\Controller\LoginController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

login_check:
    path: /login_check
    controller: App\Controller\LoginController::login

logout:
    path: /logout
    controller: App\Controller\LoginController::logout
